version: "2"
services:
  automat:
    image: automat
    build: .
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./autotables:/home/node/autotables
    restart: unless-stopped
